language: java

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: RVrbSK76Ui1JcnfAq8mV11FDkntu/BaJwOiMWIezAEZAenrwtVlnGaP2hZPRvvFV0c/jRnEv6Q1YuhB9rQ0Ldac2TWpTMomfTLzChZmhuev5Ee7bL4cCJ/gROA0cnYrixYLxpLk3yYMiZuJviDuvACzUXkll37lBIOjpXzoKB5xPN1xuw+vtMQ7L+BQLvBJkWgEDGrUMpOXNIph1fBVcANX28AAmlzZuruNdh6jyi97CfIzE5gn1HnKInn8mW1iG5C5kU6uxShVNTav1Moo9mYJTJt0WfTiDPhb6+11uDNtGjmATd73wjccpLKX7QJAqkH2i/jxPFlqB5pgmklmxCgaL/+NqRsN5Ow84bZ8uMH1j8LhdA3o79rYjeCyQ3BOnloGo2t5StXs/v/IZU1KCgCYvh4H26Bw768VsChtWtFVo+FxFoKub/AaVUmUtBTB63VKgr0iFIJSpSzMpXMFuvVBJ2y54UsOvZw1XL9IM+SYkgVBDd1fAwPT3nfNDUYfDbECzd7FbLhg0vvzhagOZCz/jbN8FEyauPFXQ4xwLoI6kKLoQSkF8qOr+dLbyXEKHSXxAt8lnIeGAJrSEmPiOv69JBirjSR0OMfaT/KL+cfQ2AJ6Hhc5XNmFQjIELP42Jmd+tmTBD2nfwY76vrU132C/nzoAGXkUME2hGbnvlrRg=
    # Encrypted `GCS_SECRET` variable.
    - secure: MJwWe0DGfHzeP3RfiJNjD+vT1ewb+kR4FJdHxpo+RxZt/NuL0MYjcjIMR9/mRmRD3KwHB0Li16tP1ACTeaGDKemZM5ApKNsBF0XuCPMP4ql0irDW0P00pWjcpqP0ofYfjM4YpueWTtqkr6c+huMxDiKjAEpBPIZdb4av4Tb7Hp1DtGliOeL5G7E2odMDhLb8C5DA27ccyeDvlSuS8Q3PmZBO7EVZ3ISWWpo57S6FTEAQS6VCwjAiV1F5OCIPytIcbIHkt41WZKm+GLZ8LAn5pcFOCzJYbGqe1KqAFVqtLtPJw01VsyXTB/v392ZioPFsOZ5K7szXO75ltaSTv8PrwF2a4TqdZ8ps1I37TcURbu4twPrqCF3ZzBlU5VQs302B2dJlvBqgIEmUJGlTqNZTe6QgEbY5F6kD59Tnlbg4fsmgFrSpeDeEsfqtSu0K2RzxLeFF2cT6fDxg9ZKSLI6KoozFKQ3yGRk/ySj2zV7t9kaf30N7IXfu+lsPetFzEe+7oTK4DWYwt+O56he/ly+xB9bBxdVYsT73Khg/VYWt78tfqoWDtZ9xt1N4cM56iLHmImTe1JBy+35wykzpBPzCl6zRYP2qRY9XERTOyue/evgqPNvV1KZtMA6PpGhOysu1HjgNcpbfonNfL3ldj5hx2/y7HNi1uZT2jy0u2hmZGYo=

before_install:
  - chmod +x gradlew

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./scripts/report-coverage.sh
  - ./scripts/report-coverage.sh
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

script:
  - ./gradlew check --stacktrace
  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_110b6513daa5_key -iv $encrypted_110b6513daa5_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar
  - ./gradlew cleanGCS --info

after_script:
  - chmod +x ./scripts/upload-artifacts.sh
  - ./scripts/upload-artifacts.sh
