language: java

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: WFrQF8XUN8u9+iD6iTI0qLzyhwY7Yzc5OqTJDY8FDs5LdkPBbJjLUSpQupakjEucX/ClnubmxAeMLF1BWS7ZqklMFGk7iuijfFinbAVmIvx1mbYqaqhBksipLCBYuY4J4zAKTl5tJNBOZL2AFrvY2sgCbzD6kf2c64HL8y116TKGCb87j+/u9vRV0bNY1pgOi4yfZabLk4Fd9NzMHXxnRrl8phVCPmTIrSNLIEQ3iwSnx/b1RCQl93M/s3QH7mBUhCQP3JDzE78xtnwCm+6mJDZbx8WMXQ8tYaM9FMmjgJ1ar72AIFowclV6/Z0TzHdhqtLcX3rSJLbsKp2ZGd8qodUwhHHFmKRY8V63+w3vQEfY3CauBEwtjmeh05wi1pIWIrfjZgBhNKT/72eVReOEDNV6sJZzeWcH+lwRmYMZLdsIqosgWrg12Qk4IeZM7zyoNKURphEdC14kjLQSI32+9DcBAOB2Jdt7WN18HGNXtdGIy7UN+Yvh1kUCMEPygEO/BS625zV5Pg10f3Zum8s3ms5Dp0YsvlXNxBfl72I5HlnRKl6wPNYEcbS8Jsd7ZotNXBoVILd7Cklh7YFqlZ/+ixmHnwLMvpSb2dc+HzTshmTph0wlCaMJvLzlqKQ7gRE+NFpubqy/wh/gCgwNrN8/RLedHUZ7zPydzq4OhLrERCE=
    # Encrypted `GCS_SECRET` variable.
    - secure: MJwWe0DGfHzeP3RfiJNjD+vT1ewb+kR4FJdHxpo+RxZt/NuL0MYjcjIMR9/mRmRD3KwHB0Li16tP1ACTeaGDKemZM5ApKNsBF0XuCPMP4ql0irDW0P00pWjcpqP0ofYfjM4YpueWTtqkr6c+huMxDiKjAEpBPIZdb4av4Tb7Hp1DtGliOeL5G7E2odMDhLb8C5DA27ccyeDvlSuS8Q3PmZBO7EVZ3ISWWpo57S6FTEAQS6VCwjAiV1F5OCIPytIcbIHkt41WZKm+GLZ8LAn5pcFOCzJYbGqe1KqAFVqtLtPJw01VsyXTB/v392ZioPFsOZ5K7szXO75ltaSTv8PrwF2a4TqdZ8ps1I37TcURbu4twPrqCF3ZzBlU5VQs302B2dJlvBqgIEmUJGlTqNZTe6QgEbY5F6kD59Tnlbg4fsmgFrSpeDeEsfqtSu0K2RzxLeFF2cT6fDxg9ZKSLI6KoozFKQ3yGRk/ySj2zV7t9kaf30N7IXfu+lsPetFzEe+7oTK4DWYwt+O56he/ly+xB9bBxdVYsT73Khg/VYWt78tfqoWDtZ9xt1N4cM56iLHmImTe1JBy+35wykzpBPzCl6zRYP2qRY9XERTOyue/evgqPNvV1KZtMA6PpGhOysu1HjgNcpbfonNfL3ldj5hx2/y7HNi1uZT2jy0u2hmZGYo=

before_install:
  - chmod +x gradlew

script:
  - ./gradlew check --stacktrace

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_110b6513daa5_key -iv $encrypted_110b6513daa5_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

  - ./gradlew cleanGCS --info

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./scripts/publish-artifacts.sh
  - ./scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./scripts/report-coverage.sh
  - ./scripts/report-coverage.sh

after_script:
  - chmod +x ./scripts/upload-artifacts.sh
  - ./scripts/upload-artifacts.sh
