language: java

env:
  global:
    # Encrypted `CODACY_PROJECT_TOKEN` variable according to:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    - secure: "15m5uN8UnYiYlQt4B9QhWdlp457hVDljtElYRETPO7qpvhw7RK1Ge93pVcSkn0gvwmlQm1DVJ3Xs4w9NcN5ooeSGZGHmCp5eRRJhQmQFQ0vRGrRYkpSX0+JAkBMJr0cHJgjlDMNtUZs6pJYFxV0tGaXfEoOwKhbCpJ0u5sDM4c7lDtvBSpiTQe1Y6gQa2OVDKBpcjkne6gG18SlR2zBbqnkAmvm6c5GWsyuUgEBSPJ8w/1itNBixwkQdKS5Y+t8eH/vOjLR3IVeNRny8CXYLFtOCJKB4Jf15FiexRNEH1gLe7+dQgj9pulwqIvZPhMdtw32eLIDkQRRB3jtHpA78hdqagrx8y1ubdPl5VfXk8Kr+jFtu0NHlfGt1QSFNtgebr9FUf6F/yAGsnLmLZid64JkW5uQIRxVBiDJO9n54EPn+n60E9KFabQpwgqu9AW37pwdRCpIBa5AruyxwOa0ScQZxNWbSg3JS6zl5RJ4eMr8G+aoZvNEgUjHt0zlEYrtWXh0QUIRK6WJBZhRx0F44qkwTu3ZahlTTqYQVgdj4CDPpwHmTD1koPgENm5NKmicXuIft6X84/He/ZzH6yhm3hUxZaSGyLT+pzdaZ7gy7DpkOvImWA2WtO6VsizOD0yIhEX/Jlwcfdl9g2xQytP5h62xa5fIwGNpioHTTp3SxaQI="
    # Encrypted `GCS_SECRET` variable.
    - secure: "map5l2RlazZyiZ3SRa6RG9KC6E624JVN+HD2WH8sVODeUbS0XlRmQ9YZYZtQM0HiiVSjFV+Pgj9nL17s20YI4BC/Zn7B/f4lMp4+La1PfmEg3vVlW/a53tGQ/lW4AKX2SdyzbFirT22c8r/MSaksKr1zMNGfQryjh65YUbqLsMjCy2bg8RS5SPxu5Cj0Y9/QDwBnkKI1OqF5O2sps7UfFFSV3UCv3DljHYVk3W62WRQgaNUNzvoi+FEk1lxmPA4aff6ZDNIgzvpUd9qR6UpBRB8vX2t93cLTGd/Ar50H5s63GYPHhhgYJxdohoK4iZUUBmerLtTrg3w9TW8dLIKo5Lp6EM8Cj/amG+DfJoAdGP2yyvFWl4cVC/kppBgjPIlBwxZgVkWBXB7kkXh6YmKm7BPDUqDvwCPbN2Rc2WRMEJlwEApHpFH1rXuknyrxaN8YRTfCe7bhxx/VZ9qB+AqiANlW6z7gg3SlgrEJCkZC9BlhGq3tCTTpP4xvgNuAJPwsjxwesTzfyh21HFStUGFEhlbuKqpGo/i45R0frrVjuJF558ZUdJv0182s7qU0GDPiDe7qsWXVPVJSkHMRt3aksHMkbXzFrWy4W0XCZWNEcdU1fjUo2lIk+w6IwXsvX58y7+Rt3sqNcjN3xj8flNw2CppLk7f4kiBmcK+vLuC6IPQ="
    # Encrypted `NPM_TOKEN` variable to enable JS publishing.
    - secure: "Gli5nNycgONYmTafxkXKXYbwTBDuEr9C6Hm18VXnv6nsr0iJLZUXHYX6Giy+GLm5tH3x+TwvtUwmO6hVouFRkSruG95kRHp4pB4yrisW9IAgWIJEmSY0E5fzm/hESBS8MRDfAxbsFNvrOT99fTEq+m8ELWz77w6ygTJWp4OWyW2uzDVKzGK8lC701YYugTiYKfUhZwngn+mlExG1zsOUlp3WJubD7O/RZMag71u/6QFB2GMDbU7+x9A4Wn3n50uhfYq8i6VKneFW7HGGQCZoCzZJHTAz77e2psF3NtAzB2uSZkcalV3zm5a27yVnKRIjnv3kEMoC1aQJ8wwavNX4cBJmmmvirF6kqZ4MIz73GNv2+QSAIhwY3svViTciB/QvAdfS+jJGTzlmgwMIVZrlTypsbKrjt6t/mf89ipEkaZXmXMBJqxJhvyCFfXCHWg3S2I3z1MgsDNaUioJc5lSfex7NQ46zfsYEqkrT5BWUiEGxi4/D76+EPmfwthL1NXdFr9Xi/4fHKuhf5fKuuu9Fxc1o1QNtDIzJPY5FPd3n6p3fn7bWa8JvzYEZeGnqb3o7ezMveRhM09cHmv1Hc/Y25rONNKiSgl3Pb76Nj/5Jdh1txdGdzddpzayi9a4ipZcFlwlN4Jl57re0+96+enQor99h5qXogEtg3WdbsQv7obA="

before_install:
  - chmod +x gradlew

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_6b4661b8f8bf_key -iv $encrypted_6b4661b8f8bf_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
  - ./gradlew check --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)
  - chmod +x ./config/scripts/report-coverage.sh
  - ./config/scripts/report-coverage.sh

after_script:
  - chmod +x ./scripts/upload-artifacts.sh
  - ./config/scripts/upload-artifacts.sh
