language: java

env:
  global:
    # https://docs.travis-ci.com/user/environment-variables/#Encrypting-environment-variables
    # Encrypted `GCS_SECRET` variable.
    - secure: "map5l2RlazZyiZ3SRa6RG9KC6E624JVN+HD2WH8sVODeUbS0XlRmQ9YZYZtQM0HiiVSjFV+Pgj9nL17s20YI4BC/Zn7B/f4lMp4+La1PfmEg3vVlW/a53tGQ/lW4AKX2SdyzbFirT22c8r/MSaksKr1zMNGfQryjh65YUbqLsMjCy2bg8RS5SPxu5Cj0Y9/QDwBnkKI1OqF5O2sps7UfFFSV3UCv3DljHYVk3W62WRQgaNUNzvoi+FEk1lxmPA4aff6ZDNIgzvpUd9qR6UpBRB8vX2t93cLTGd/Ar50H5s63GYPHhhgYJxdohoK4iZUUBmerLtTrg3w9TW8dLIKo5Lp6EM8Cj/amG+DfJoAdGP2yyvFWl4cVC/kppBgjPIlBwxZgVkWBXB7kkXh6YmKm7BPDUqDvwCPbN2Rc2WRMEJlwEApHpFH1rXuknyrxaN8YRTfCe7bhxx/VZ9qB+AqiANlW6z7gg3SlgrEJCkZC9BlhGq3tCTTpP4xvgNuAJPwsjxwesTzfyh21HFStUGFEhlbuKqpGo/i45R0frrVjuJF558ZUdJv0182s7qU0GDPiDe7qsWXVPVJSkHMRt3aksHMkbXzFrWy4W0XCZWNEcdU1fjUo2lIk+w6IwXsvX58y7+Rt3sqNcjN3xj8flNw2CppLk7f4kiBmcK+vLuC6IPQ="
    # Encrypted `NPM_TOKEN` variable to enable JS publishing.
    - secure: "hXD4uJi2Jh/m4mZXABfG21qf7Day0Ye8fEkAcKQzkgEf3CmGOXKPbnP5rz5e1ESEp4XOypCndAb0QEv3MYV+kTvl62pKq0TxmVjB27qVTHJMVXpZ3cz9ED94nUqRj6d+uhmHuQJWxRsaWsspBV/+jyIx48zc1Lvzpu+gT05kDq55RoSX8A98FQIY/typf2qVWdnOv3hTdZiXpgLe2qv3FgaF5jFRppy1PB7d5rZGjBeQNyZ8kxOFeF5n5Jwbvz3Q3XcSP91kt724o8VKay6EKyF226x8Hcb5NFRnmjdzyD0AFdIJMxaGg1eqdVYftxDrW5HjE1uVlZ5bPzIxjX6BZ6yWY24larwQeX31mFVQeJVSa88zuaSX9BRgbdoubZAMrGZaxKyX4BvXNwqZKAnxMHnS9cRcmv06bwNnw8AbJ0ULPN8/T41ma/YA+//rZhxCPc3TN8UDAMFoTxfBaSgjEG2es26eOUPqAZNsWA+OMCTnLJpaYynFanOILeaiiFeCMjEKnHo+N/oeJuNQnYCXqb7ZHPjwgsuTjaBDq1qbTph43wDeHfy7t4zrMoYmB7oK9WOrJJbtO5jBBAJGVJx7PhZaU6JFsbi/UDlsilw6kR9sdOEk/1ukYfJBNs0VXCT5RFB92JqWGqvwZUIkHHa61l24BmD/HoNjiWGKYAVPkwk="

before_install:
  - chmod +x gradlew

  # Upgrade the `npm` version shipped with Travis to the latest.
  - npm install -g npm@latest

  # Decrypt and unarchive Maven and Google Cloud Storage credentials.
  - openssl aes-256-cbc -K $encrypted_6b4661b8f8bf_key -iv $encrypted_6b4661b8f8bf_iv -in credentials.tar.enc -out credentials.tar -d
  - tar xvf credentials.tar

script:
  - ./gradlew check --stacktrace

  # The publishing script should be executed in `script` section in order to
  # fail the Travis build if execution of this script is failed.
  - chmod +x ./config/scripts/publish-artifacts.sh
  - ./config/scripts/publish-artifacts.sh

after_success:
  # See: https://github.com/codecov/example-java/blob/master/.travis.yml
  - bash <(curl -s https://codecov.io/bash)

after_script:
  - chmod +x ./scripts/upload-artifacts.sh
  - ./config/scripts/upload-artifacts.sh
